const SECURITY = {
  'cache-control': 'no-store',
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'x-frame-options': 'DENY',
  'content-security-policy': "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",
  'permissions-policy': 'camera=(), microphone=(), display-capture=(), geolocation=(), payment=(), usb=()',
  'strict-transport-security': 'max-age=31536000; includeSubDomains'
};
const JSON_HEADERS={...SECURITY,'content-type':'application/json; charset=utf-8'};
const CONTROL_ORIGIN='https://slc.skyfirst.io.vn';
const MANUAL_TYPES=new Set(['essay','long','structured','file','image','audio','math']);
const ATTACHMENT_TYPES=new Set(['file','image','audio']);
const str=v=>String(v??'').trim();
const safeJson=(v,f)=>{try{return JSON.parse(v)}catch{return f}};
const nowIso=()=>new Date().toISOString();
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}});
const ok=(body={})=>json({ok:true,...body});
const bad=(message,status=400,detail)=>json({ok:false,message,detail},status);
function withSecurity(response){if(!response||response.status===101)return response;const h=new Headers(response.headers);for(const [k,v] of Object.entries(SECURITY))h.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
function databaseTimeMs(value){const raw=str(value);if(!raw)return NaN;const utc=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:\.\d+)?$/.test(raw)?raw.replace(' ','T')+'Z':raw;return Date.parse(utc)}
function examTimeMs(value){const raw=str(value);if(!raw)return null;const explicit=/(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw);const ms=Date.parse(explicit?raw:raw.replace(' ','T')+'+07:00');return Number.isFinite(ms)?ms:null}
function bearerToken(request){const m=str(request.headers.get('authorization')).match(/^Bearer\s+([A-Za-z0-9._~-]{16,512})$/i);return m?m[1]:''}
async function sha256Text(value){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function publicQuestions(raw='[]'){const qs=Array.isArray(raw)?raw:safeJson(raw,[]);return qs.map(q=>{const clean={...(q&&typeof q==='object'?q:{})};for(const key of ['answer','answer_json','correct','solution','explanation','rubric','rubric_json','scoring','scoring_config'])delete clean[key];return clean})}
function assessmentScoreVisible(exam={},now=Date.now()){if(Number(exam.show_score)===0)return false;const release=examTimeMs(exam.result_release_at);if(release&&now<release)return false;const policy=str(exam.result_policy||'score_after_submit');if(policy==='score_after_submit'||policy==='score_total_only')return true;if(policy==='full_review_after_close'){const close=examTimeMs(exam.closes_at);return exam.exam_status==='closed'||exam.status==='closed'||!!(close&&now>=close)}return false}
function normalizeValue(v){return str(v).replace(/\s+/g,' ').toLocaleLowerCase('vi-VN')}
function answerEqual(q,actual){const type=str(q?.type),expected=q?.answer;
  if(type==='mcq'||type==='truefalse')return String(actual??'')===String(expected??'');
  if(type==='fill'||type==='short'){let accepted=[];try{const x=typeof expected==='string'?JSON.parse(expected):expected;accepted=Array.isArray(x)?x:[x]}catch{accepted=String(expected??'').split('|')}return accepted.some(x=>normalizeValue(x)===normalizeValue(actual))}
  if(type==='numeric'){const a=Number(actual),e=Number(expected),tol=Math.max(0,Number(q.numeric_tolerance??q.tolerance??0));return Number.isFinite(a)&&Number.isFinite(e)&&Math.abs(a-e)<=tol}
  if(type==='multi'||type==='ordering'){let ex=[];try{ex=Array.isArray(expected)?expected:JSON.parse(expected||'[]')}catch{}const ac=Array.isArray(actual)?actual:[];return type==='multi'?JSON.stringify(ac.map(String).sort())===JSON.stringify(ex.map(String).sort()):JSON.stringify(ac.map(String))===JSON.stringify(ex.map(String))}
  if(type==='matching'){let ex={};try{ex=expected&&typeof expected==='object'?expected:JSON.parse(expected||'{}')}catch{}const ac=actual&&typeof actual==='object'&&!Array.isArray(actual)?actual:{};const keys=Object.keys(ex);return keys.length>0&&keys.every(k=>String(ac[k]??'')===String(ex[k]??''))}
  return false
}
function autoScore(qs=[],answers={}){let score=0,max=0,manual=[];for(const q of qs){const pts=Math.max(0,Number(q.points||1));max+=pts;if(MANUAL_TYPES.has(str(q.type))){manual.push(q);continue}if(answerEqual(q,answers[q.id]))score+=pts}return {score,max,manual}}
async function seedManual(env,attemptId,questions=[]){for(const q of questions.filter(x=>MANUAL_TYPES.has(str(x.type))))await env.DB.prepare(`INSERT OR IGNORE INTO assessment_manual_grades(id,attempt_id,question_id,grader_user_id,score,feedback,status,created_at,updated_at) VALUES(?,?,?,'system',NULL,'','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),attemptId,str(q.id)).run().catch(()=>{})}
function attemptDeadline(a){return Number(a.time_limit_enabled)===0?null:databaseTimeMs(a.started_at)+(Number(a.duration_minutes||60)+Number(a.extra_time_minutes||0))*60000}
function candidateFrom(a,source){return source==='guest'?{full_name:a.full_name||'',candidate_code:a.candidate_code||'',class_name:a.class_name||''}:{full_name:a.full_name||'',candidate_code:a.sfn_id||'',class_name:a.class_name||''}}
function sessionId(request){const id=str(request.headers.get('x-exam-session'));return /^[A-Za-z0-9._~-]{16,160}$/.test(id)?id:''}
function applySealedPackage(row){if(!row)return row;const pack=safeJson(row.package_json,null);if(!pack||typeof pack!=='object')return row;const timing=pack.timing&&typeof pack.timing==='object'?pack.timing:{},pol=pack.policies&&typeof pack.policies==='object'?pack.policies:{};const bit=(v,f)=>v===undefined?f:(v?1:0);return {...row,duration_minutes:timing.duration_minutes??row.duration_minutes,time_limit_enabled:bit(timing.time_limit_enabled,row.time_limit_enabled),strict_mode:bit(pol.strict_mode,row.strict_mode),fullscreen_required:bit(pol.fullscreen_required,row.fullscreen_required),allow_clipboard:bit(pol.allow_clipboard,row.allow_clipboard),allow_paste:bit(pol.allow_paste,row.allow_paste),allow_external_links:bit(pol.allow_external_links,row.allow_external_links),security_profile:pol.security_profile||row.security_profile,device_policy:pol.device_policy||row.device_policy,resume_policy:pol.resume_policy||row.resume_policy,calculator_policy:pol.calculator_policy||row.calculator_policy}}
async function claimLease(env,source,attemptId,request){const sid=sessionId(request);if(!sid)throw Object.assign(new Error('SESSION_REQUIRED'),{status:409,detail:{code:'SESSION_REQUIRED'}});await env.DB.prepare(`INSERT OR IGNORE INTO assessment_attempt_leases(attempt_id,source,session_id,claimed_at,last_seen_at) VALUES(?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(attemptId,source,sid).run();const lease=await env.DB.prepare(`SELECT session_id FROM assessment_attempt_leases WHERE attempt_id=? AND source=?`).bind(attemptId,source).first();if(!lease||lease.session_id!==sid)throw Object.assign(new Error('SESSION_CONFLICT'),{status:409,detail:{code:'SESSION_CONFLICT'}});return sid}
async function authorize(env,source,attemptId,request){const raw=bearerToken(request);if(!raw)throw Object.assign(new Error('AUTH'),{status:401});if(source==='guest'){const row=await env.DB.prepare(`SELECT a.*,e.title,e.instructions,e.duration_minutes,e.time_limit_enabled,e.strict_mode,e.fullscreen_required,e.show_score,e.assessment_type,e.assessment_label,e.center_label,e.result_policy,e.result_release_at,e.closes_at,e.status exam_status,e.security_profile,e.allow_clipboard,e.allow_paste,e.allow_external_links,e.device_policy,e.resume_policy,e.calculator_policy,v.snapshot_json package_json,COALESCE(a.question_snapshot_json,e.question_json) question_json FROM exam_guest_attempts a JOIN exams e ON e.id=a.exam_id LEFT JOIN assessment_exam_versions v ON v.id=COALESCE(a.exam_version_id,e.sealed_version_id) WHERE a.id=? AND a.access_key=?`).bind(attemptId,raw).first();if(!row)throw Object.assign(new Error('AUTH'),{status:401});return applySealedPackage(row)}
  const hash=await sha256Text(raw);const row=await env.DB.prepare(`SELECT a.*,e.title,e.instructions,e.duration_minutes,e.time_limit_enabled,e.strict_mode,e.fullscreen_required,e.show_score,e.assessment_type,e.assessment_label,e.center_label,e.result_policy,e.result_release_at,e.closes_at,e.status exam_status,e.security_profile,e.allow_clipboard,e.allow_paste,e.allow_external_links,e.device_policy,e.resume_policy,e.calculator_policy,v.snapshot_json package_json,COALESCE(a.question_snapshot_json,e.question_json) question_json,u.full_name,u.sfn_id,u.email,c.name class_name FROM exam_access_tokens t JOIN exam_attempts a ON a.id=t.attempt_id AND a.user_id=t.user_id JOIN exams e ON e.id=a.exam_id LEFT JOIN assessment_exam_versions v ON v.id=COALESCE(a.exam_version_id,e.sealed_version_id) JOIN users u ON u.id=a.user_id LEFT JOIN classes c ON c.id=e.class_id WHERE t.token_hash=? AND t.attempt_id=? AND datetime(t.expires_at)>CURRENT_TIMESTAMP AND u.status='active'`).bind(hash,attemptId).first();if(!row)throw Object.assign(new Error('AUTH'),{status:401});return applySealedPackage(row)}
async function receiptFor(env,a){let r=await env.DB.prepare(`SELECT receipt_code FROM assessment_receipts WHERE attempt_id=? ORDER BY created_at DESC LIMIT 1`).bind(a.id).first().catch(()=>null);if(!r){const code=`SLC-${String(a.id).slice(0,8).toUpperCase()}`;await env.DB.prepare(`INSERT OR IGNORE INTO assessment_receipts(id,attempt_id,receipt_code,payload_json,created_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),a.id,code,JSON.stringify({attempt_id:a.id,exam_id:a.exam_id,status:'submitted'})).run().catch(()=>{});r={receipt_code:code}}return r?.receipt_code||`SLC-${String(a.id).slice(0,8).toUpperCase()}`}
async function finalResponse(env,a){const pending=await env.DB.prepare(`SELECT COUNT(*) n FROM assessment_manual_grades WHERE attempt_id=? AND status!='published'`).bind(a.id).first().catch(()=>({n:0}));const visible=assessmentScoreVisible(a)&&Number(pending?.n||0)===0;return {submitted:true,status:'submitted',score:visible?a.score:null,max_score:visible?a.max_score:null,show_score:visible,pending_manual:Number(pending?.n||0),receipt_code:await receiptFor(env,a)}}
async function validateAttachmentAnswers(env,attemptId,qs,answers){for(const q of qs){if(!ATTACHMENT_TYPES.has(str(q.type)))continue;const v=answers?.[q.id];if(v==null||v==='')continue;const fileId=str(v?.file_id);if(!fileId)throw Object.assign(new Error('Tệp trả lời không hợp lệ.'),{status:400});const row=await env.DB.prepare(`SELECT 1 ok FROM assessment_response_files WHERE attempt_id=? AND question_id=? AND file_id=? AND status='active'`).bind(attemptId,str(q.id),fileId).first();if(!row)throw Object.assign(new Error('Tệp trả lời không thuộc câu hỏi này.'),{status:403})}}
async function finalize(env,source,a,body,afterDeadline=false){if(a.status==='submitted')return finalResponse(env,a);if(a.status!=='in_progress')throw Object.assign(new Error('Phiên thi không còn hoạt động.'),{status:409,detail:{status:a.status}});const qs=safeJson(a.question_json,[]);const answers=afterDeadline?safeJson(a.answers_json,{}):(body?.answers&&typeof body.answers==='object'?body.answers:{});await validateAttachmentAnswers(env,a.id,qs,answers);const scored=autoScore(qs,answers),events=Array.isArray(body?.events)?body.events.slice(-400):safeJson(a.event_log_json,[]);const change=await env.DB.prepare(`UPDATE ${source==='guest'?'exam_guest_attempts':'exam_attempts'} SET answers_json=?,event_log_json=?,score=?,max_score=?,status='submitted',submitted_at=COALESCE(submitted_at,CURRENT_TIMESTAMP),last_saved_at=COALESCE(last_saved_at,CURRENT_TIMESTAMP) WHERE id=? AND status='in_progress'`).bind(JSON.stringify(answers),JSON.stringify(events),scored.score,scored.max,a.id).run();if(!Number(change?.meta?.changes||0)){const current=await env.DB.prepare(`SELECT a.*,e.show_score,e.result_policy,e.result_release_at,e.closes_at,e.status exam_status FROM ${source==='guest'?'exam_guest_attempts':'exam_attempts'} a JOIN exams e ON e.id=a.exam_id WHERE a.id=?`).bind(a.id).first();if(current?.status==='submitted')return finalResponse(env,current);throw Object.assign(new Error('Phiên thi đã thay đổi trạng thái.'),{status:409,detail:{status:current?.status||'unknown'}})}await seedManual(env,a.id,scored.manual);await env.DB.prepare(`INSERT INTO assessment_result_workflows(attempt_id,source,state,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(attempt_id) DO UPDATE SET source=excluded.source,state=excluded.state,updated_at=CURRENT_TIMESTAMP`).bind(a.id,source,scored.manual.length?'marking':'graded').run().catch(()=>{});const fresh={...a,status:'submitted',score:scored.score,max_score:scored.max};return finalResponse(env,fresh)}
async function getAttempt(env,source,attemptId,request){const a=await authorize(env,source,attemptId,request);await claimLease(env,source,attemptId,request);if(a.status==='submitted')throw Object.assign(new Error('Phiên thi đã được nộp.'),{status:409,detail:{...(await finalResponse(env,a)),status:'submitted'}});if(a.status!=='in_progress')throw Object.assign(new Error('Phiên thi đã kết thúc.'),{status:409,detail:{status:a.status}});const deadline=attemptDeadline(a);if(deadline&&Date.now()>=deadline){const result=await finalize(env,source,a,{},true);throw Object.assign(new Error('Đã hết thời gian. Bài làm đã được khóa và nộp.'),{status:409,detail:result})}return ok({attempt_id:a.id,exam:{id:a.exam_id,title:a.title,instructions:a.instructions,duration_minutes:a.duration_minutes,time_limit_enabled:Number(a.time_limit_enabled)!==0,strict_mode:Number(a.strict_mode)!==0,fullscreen_required:Number(a.fullscreen_required)!==0,show_score:Number(a.show_score)!==0,assessment_type:a.assessment_type,assessment_label:a.assessment_label,center_label:a.center_label,security_profile:a.security_profile||'STANDARD',allow_clipboard:Number(a.allow_clipboard)!==0,allow_paste:Number(a.allow_paste)!==0,allow_external_links:Number(a.allow_external_links)!==0,device_policy:a.device_policy||'single_session',resume_policy:a.resume_policy||'same_session',calculator_policy:a.calculator_policy||'disabled',questions:publicQuestions(a.question_json)},candidate:candidateFrom(a,source),answers:safeJson(a.answers_json,{}),events:safeJson(a.event_log_json,[]),remaining_seconds:deadline?Math.max(0,Math.ceil((deadline-Date.now())/1000)):null,answer_revision:Number(a.answer_revision||0),last_saved_at:a.last_saved_at||null,server_time:nowIso(),deadline_at:deadline?new Date(deadline).toISOString():null})}
async function saveAttempt(env,source,attemptId,request){const a=await authorize(env,source,attemptId,request);await claimLease(env,source,attemptId,request);if(a.status==='submitted')throw Object.assign(new Error('Bài làm đã được nộp.'),{status:409,detail:{...(await finalResponse(env,a)),status:'submitted'}});if(a.status!=='in_progress')throw Object.assign(new Error('Phiên thi không còn hoạt động.'),{status:409,detail:{status:a.status}});const deadline=attemptDeadline(a);if(deadline&&Date.now()>=deadline){const result=await finalize(env,source,a,{},true);throw Object.assign(new Error('Đã hết thời gian. Bài làm đã được khóa và nộp.'),{status:409,detail:result})}const body=await request.json();if(JSON.stringify(body.answers||{}).length>2_000_000)throw Object.assign(new Error('Dữ liệu bài làm vượt giới hạn an toàn.'),{status:413});const qs=safeJson(a.question_json,[]);await validateAttachmentAnswers(env,a.id,qs,body.answers||{});const clientRev=Number(body.revision??a.answer_revision??0);if(clientRev!==Number(a.answer_revision||0))throw Object.assign(new Error('Bài làm trên máy chủ đã có phiên bản mới hơn.'),{status:409,detail:{code:'REVISION_CONFLICT',answer_revision:Number(a.answer_revision||0)}});const events=Array.isArray(body.events)?body.events.slice(-400):safeJson(a.event_log_json,[]),nextRev=Number(a.answer_revision||0)+1,table=source==='guest'?'exam_guest_attempts':'exam_attempts';const wr=await env.DB.prepare(`UPDATE ${table} SET answers_json=?,event_log_json=?,answer_revision=?,last_saved_at=CURRENT_TIMESTAMP WHERE id=? AND status='in_progress' AND answer_revision=?`).bind(JSON.stringify(body.answers||{}),JSON.stringify(events),nextRev,a.id,Number(a.answer_revision||0)).run();if(!Number(wr?.meta?.changes||0))throw Object.assign(new Error('Bài làm vừa được cập nhật ở phiên khác.'),{status:409,detail:{code:'REVISION_CONFLICT'}});await env.DB.prepare(`INSERT OR IGNORE INTO assessment_answer_revisions(id,attempt_id,source,revision,answers_json,events_json,accepted_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),a.id,source,nextRev,JSON.stringify(body.answers||{}),JSON.stringify(events)).run().catch(()=>{});return ok({saved_at:nowIso(),answer_revision:nextRev})}
async function submitAttempt(env,source,attemptId,request){const a=await authorize(env,source,attemptId,request);await claimLease(env,source,attemptId,request);if(a.status==='submitted')return ok(await finalResponse(env,a));if(a.status!=='in_progress')throw Object.assign(new Error('Phiên thi không còn hoạt động.'),{status:409,detail:{status:a.status}});const body=await request.json().catch(()=>({})),deadline=attemptDeadline(a),afterDeadline=!!(deadline&&Date.now()>=deadline);if(!afterDeadline&&body.revision!=null&&Number(body.revision)!==Number(a.answer_revision||0))throw Object.assign(new Error('Bài làm trên máy chủ đã có phiên bản mới hơn.'),{status:409,detail:{code:'REVISION_CONFLICT',answer_revision:Number(a.answer_revision||0)}});return ok(await finalize(env,source,a,body,afterDeadline))}
async function recordViolation(env,source,attemptId,request){const a=await authorize(env,source,attemptId,request);await claimLease(env,source,attemptId,request);if(a.status!=='in_progress')throw Object.assign(new Error('Phiên thi không còn hoạt động.'),{status:409,detail:{status:a.status}});const deadline=attemptDeadline(a);if(deadline&&Date.now()>=deadline){const result=await finalize(env,source,a,{},true);throw Object.assign(new Error('Đã hết thời gian.'),{status:409,detail:result})}const body=await request.json(),reason=str(body.reason).slice(0,300)||'integrity_event',events=Array.isArray(body.events)?body.events.slice(-400):safeJson(a.event_log_json,[]),table=source==='guest'?'exam_guest_attempts':'exam_attempts';await env.DB.prepare(`UPDATE ${table} SET event_log_json=?,last_saved_at=COALESCE(last_saved_at,CURRENT_TIMESTAMP) WHERE id=? AND status='in_progress'`).bind(JSON.stringify(events),a.id).run();await env.DB.prepare(`INSERT INTO exam_audit_log(id,exam_id,attempt_id,actor_user_id,event_type,detail_json) VALUES(?,?,?,?,?,?)`).bind(crypto.randomUUID(),a.exam_id,a.id,source==='guest'?null:a.user_id,'integrity.signal',JSON.stringify({reason,source})).run().catch(()=>{});return ok({recorded:true,terminated:false})}
function safeName(name='file'){return String(name).normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(0,100)||'file'}
function mimeAllowed(file,type,bytes){const mime=str(file.type).toLowerCase(),head=[...bytes.slice(0,12)],isPdf=head[0]===0x25&&head[1]===0x50&&head[2]===0x44&&head[3]===0x46,isJpg=head[0]===0xff&&head[1]===0xd8&&head[2]===0xff,isPng=head.slice(0,8).join(',')==='137,80,78,71,13,10,26,10',isWebp=String.fromCharCode(...head.slice(0,4))==='RIFF'&&String.fromCharCode(...head.slice(8,12))==='WEBP',isZip=head[0]===0x50&&head[1]===0x4b,isMp3=(head[0]===0x49&&head[1]===0x44&&head[2]===0x33)||(head[0]===0xff&&(head[1]&0xe0)===0xe0),isMp4=String.fromCharCode(...head.slice(4,8))==='ftyp';if(type==='image')return (mime.startsWith('image/jpeg')&&isJpg)||(mime.startsWith('image/png')&&isPng)||(mime.startsWith('image/webp')&&isWebp);if(type==='audio')return (mime.includes('mpeg')&&isMp3)||(mime.includes('mp4')&&isMp4)||(mime.includes('m4a')&&isMp4)||(mime.includes('wav')&&String.fromCharCode(...head.slice(0,4))==='RIFF');return isPdf||isJpg||isPng||isWebp||isZip||isMp3||isMp4||mime.startsWith('text/plain')||mime.startsWith('text/csv')}
async function uploadAttachment(env,source,attemptId,request){const a=await authorize(env,source,attemptId,request);await claimLease(env,source,attemptId,request);if(a.status!=='in_progress')throw Object.assign(new Error('Phiên thi không còn hoạt động.'),{status:409,detail:{status:a.status}});const deadline=attemptDeadline(a);if(deadline&&Date.now()>=deadline){const result=await finalize(env,source,a,{},true);throw Object.assign(new Error('Đã hết thời gian.'),{status:409,detail:result})}const fd=await request.formData(),file=fd.get('file'),questionId=str(fd.get('question_id'));if(!(file instanceof File)||!file.size||!questionId)throw Object.assign(new Error('Thiếu tệp hoặc mã câu hỏi.'),{status:400});const q=safeJson(a.question_json,[]).find(x=>String(x.id)===questionId);if(!q||!ATTACHMENT_TYPES.has(str(q.type)))throw Object.assign(new Error('Câu hỏi này không nhận tệp đính kèm.'),{status:400});const max=q.type==='audio'?50*1024*1024:30*1024*1024;if(file.size>max)throw Object.assign(new Error(`Tệp vượt quá ${Math.round(max/1024/1024)}MB.`),{status:413});const bytes=new Uint8Array(await file.slice(0,32).arrayBuffer());if(!mimeAllowed(file,q.type,bytes))throw Object.assign(new Error('Định dạng tệp không phù hợp hoặc chữ ký tệp không hợp lệ.'),{status:415});const id=crypto.randomUUID(),key=`exam-responses/${a.exam_id}/${a.id}/${questionId}/${id}-${safeName(file.name)}`;await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});try{await env.DB.batch([env.DB.prepare(`UPDATE assessment_response_files SET status='replaced' WHERE attempt_id=? AND question_id=? AND status='active'`).bind(a.id,questionId),env.DB.prepare(`INSERT INTO files(id,owner_user_id,r2_key,name,mime,size,visibility,created_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(id,source==='guest'?null:a.user_id,key,file.name,file.type||'',file.size,'private'),env.DB.prepare(`INSERT INTO assessment_response_files(id,attempt_id,source,question_id,file_id,status,created_at) VALUES(?,?,?,?,?,'active',CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),a.id,source,questionId,id)])}catch(error){await env.FILES.delete(key).catch(()=>{});throw error}return ok({file:{file_id:id,name:file.name,mime:file.type||'',size:file.size}})}
async function redeemLaunch(env,request){const body=await request.json(),raw=str(body.launch_token);if(!raw)return bad('Thiếu mã khởi chạy.',400);const hash=await sha256Text(raw),row=await env.DB.prepare(`SELECT token_hash,user_id,attempt_id,expires_at,used_at FROM exam_launch_tokens WHERE token_hash=?`).bind(hash).first();if(!row||row.used_at||Date.parse(row.expires_at)<=Date.now())return bad('Mã khởi chạy không hợp lệ hoặc đã hết hạn.',401);const accessBytes=new Uint8Array(32);crypto.getRandomValues(accessBytes);const access=[...accessBytes].map(x=>x.toString(16).padStart(2,'0')).join(''),accessHash=await sha256Text(access),exp=new Date(Date.now()+12*60*60*1000).toISOString();const batch=await env.DB.batch([env.DB.prepare(`UPDATE exam_launch_tokens SET used_at=CURRENT_TIMESTAMP WHERE token_hash=? AND used_at IS NULL`).bind(hash),env.DB.prepare(`INSERT INTO exam_access_tokens(token_hash,user_id,attempt_id,expires_at,created_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP)`).bind(accessHash,row.user_id,row.attempt_id,exp)]);if(!Number(batch?.[0]?.meta?.changes||0))return bad('Mã khởi chạy đã được sử dụng.',409);const candidate=await env.DB.prepare(`SELECT u.full_name,u.sfn_id candidate_code,c.name class_name FROM exam_attempts a JOIN users u ON u.id=a.user_id JOIN exams e ON e.id=a.exam_id LEFT JOIN classes c ON c.id=e.class_id WHERE a.id=?`).bind(row.attempt_id).first().catch(()=>null);return ok({attempt_id:row.attempt_id,access_token:access,expires_at:exp,candidate:candidate||{}})}
async function health(env){let schema=false;try{await env.DB.prepare(`SELECT 1 FROM assessment_attempt_leases LIMIT 1`).all();schema=true}catch{}return json({ok:schema,service:'Sky First Exam',version:'4.0.0',status:schema?'available':'degraded',runtime:{attempt_api:schema?'local-d1':'unavailable',control_plane:'independent-after-launch'},time:nowIso()},schema?200:503)}
async function proxyToControl(request){const src=new URL(request.url),target=new URL(src.pathname+src.search,CONTROL_ORIGIN),headers=new Headers(request.headers);headers.delete('host');headers.delete('x-exam-session');const init={method:request.method,headers,redirect:'manual'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;const response=await fetch(new Request(target,init));return withSecurity(response)}
async function api(request,env){const url=new URL(request.url),path=url.pathname,method=request.method.toUpperCase();if(method==='OPTIONS')return new Response(null,{status:204,headers:SECURITY});if(path==='/health')return health(env);if(path==='/api/public/exam-launch/redeem'&&method==='POST')return redeemLaunch(env,request);
  const guest=path.match(/^\/api\/public\/exam-attempts\/([^/]+)(?:\/(save|submit|violation|upload))?$/);if(guest){const id=decodeURIComponent(guest[1]),action=guest[2]||'';if(!action&&method==='GET')return getAttempt(env,'guest',id,request);if(action==='save'&&method==='POST')return saveAttempt(env,'guest',id,request);if(action==='submit'&&method==='POST')return submitAttempt(env,'guest',id,request);if(action==='violation'&&method==='POST')return recordViolation(env,'guest',id,request);if(action==='upload'&&method==='POST')return uploadAttachment(env,'guest',id,request)}
  const internal=path.match(/^\/api\/exam-attempts\/([^/]+)(?:\/(save|submit|violation|upload))?$/);if(internal){const id=decodeURIComponent(internal[1]),action=internal[2]||'';if(!action&&method==='GET')return getAttempt(env,'internal',id,request);if(action==='save'&&method==='POST')return saveAttempt(env,'internal',id,request);if(action==='submit'&&method==='POST')return submitAttempt(env,'internal',id,request);if(action==='violation'&&method==='POST')return recordViolation(env,'internal',id,request);if(action==='upload'&&method==='POST')return uploadAttachment(env,'internal',id,request)}
  if(path.startsWith('/api/'))return proxyToControl(request);return null
}
export default {async fetch(request,env){try{const apiResponse=await api(request,env);if(apiResponse)return withSecurity(apiResponse);const response=await env.ASSETS.fetch(request);return withSecurity(response)}catch(error){const status=Number(error?.status)||500,detail=error?.detail||undefined,message=status===401?'Quyền truy cập phiên thi không hợp lệ hoặc đã hết hạn.':status===403?'Bạn không có quyền thực hiện thao tác này.':error?.message==='SESSION_REQUIRED'?'Phiên thi cần mã phiên thiết bị hợp lệ.':error?.message==='SESSION_CONFLICT'?'Phiên thi đang được sử dụng trên tab hoặc thiết bị khác.':status>=500?'Dịch vụ dự thi đang gặp sự cố. Bài lưu trên thiết bị vẫn được giữ.':String(error?.message||'Không thể xử lý yêu cầu.');return bad(message,status,detail)}}};
